# Scanner ignore patterns for Phase 3+ features
# Used by check_streamlit_issues.py to suppress false positives.
# Document WHY each item is ignored to prevent hiding real bugs.
#
# Updated: 2026-01-20

false_positives:
  # ============================================================================
  # 06_游닌_multi_format_import.py - Structurally guaranteed corners list
  # ============================================================================
  # The corners list is ALWAYS built with exactly 8 elements via:
  #   for end_pt in [point1, point2]:    # 2 iterations
  #     for w_sign in [-1, 1]:           # 2 iterations
  #       for d_sign in [-1, 1]:         # 2 iterations = 8 total
  # Accessing corners[0-7] is structurally guaranteed safe.
  - file: "streamlit_app/pages/06_游닌_multi_format_import.py"
    lines: [834, 835, 836, 875, 876, 877, 880, 881, 882, 885, 886, 887, 890, 891, 892, 896, 897, 898, 901, 902, 903, 906, 907, 908, 911, 912, 913, 917, 918, 919, 922, 923]
    reason: "corners list is structurally guaranteed to have 8 elements (2칑2칑2 loop)"

  # int() conversions on hex color strings - known format
  - file: "streamlit_app/pages/06_游닌_multi_format_import.py"
    lines: [756, 757, 758]
    reason: "Converting hex color components - known 2-char format from base_color[n:m]"

  # Additional corners list access lines (924-943) and edge tuple access
  - file: "streamlit_app/pages/06_游닌_multi_format_import.py"
    lines: [924, 927, 928, 929, 932, 933, 934, 941, 942, 943]
    reason: "corners list (8 elements guaranteed) and edge tuples (3 elements guaranteed)"

  # ============================================================================
  # 05_3d_viewer_demo.py - Lazy imports inside button handlers
  # ============================================================================
  # tempfile/os imports inside export button handlers are intentional
  # lazy imports to reduce initial page load time
  - file: "streamlit_app/pages/05_3d_viewer_demo.py"
    lines: [263, 264, 317, 318]
    reason: "Lazy imports in button handlers - intentional to reduce page load time"

  # ============================================================================
  # Existing entries from Phase 3
  # ============================================================================
  - file: "streamlit_app/pages/08_游늵_batch_design.py"
    lines: [38, 99, 277, 279, 281]
    reason: "Division operations on CSV-validated numeric data with upstream checks"

  - file: "streamlit_app/pages/09_游댧_advanced_analysis.py"
    lines: [38, 156, 157]
    reason: "Division on st.number_input validated parameters (never zero)"

  - file: "streamlit_app/pages/11_游꿟_demo_showcase.py"
    lines: [36, 328, 440, 486]
    reason: "Division on hardcoded demo scenario values (never zero)"

  - file: "streamlit_app/pages/07_游닌_multi_format_import.py"
    lines: [296]
    reason: "Division guarded by 'if ast_mm2 > 0' conditional (never zero)"

  - file: "streamlit_app/pages/10_游뱄_ai_assistant.py"
    lines: [196, 197, 235, 236, 257, 258, 973, 982]
    reason: "Legacy fallback page - division operations guarded by upstream checks (e.g., 'if total_beams == 0: return', loop over positive area values)"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [583, 973, 1005, 1012, 1237, 1244, 1258, 1443, 1679, 1700, 1858]
    reason: "All division operations have upstream guards: max(x, 1), 'if length < 0.01: continue', 'if d_eff > 0', etc."

  # ai_workspace.py - Session 63+ analysis
  # Division issues are guarded but scanner doesn't detect the pattern
  - file: "streamlit_app/components/ai_workspace.py"
    lines: [662]
    reason: "Division by BAR_OPTIONS area values (always positive constants)"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [1091, 1121]
    reason: "Division guarded by upstream length/geometry checks"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [1547, 1548, 1553, 1556, 1562]
    reason: "Division guarded by 'if ... == 0: continue' loops"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [1701, 1734, 1741]
    reason: "Division with max(x, 1) guards ensuring non-zero denominator"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [2080, 2083, 2093, 2099, 2142, 2150]
    reason: "Division guarded by 'if d_eff <= 0 or fy <= 0: return None' at line 2077"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [2187, 2204, 2205, 2295, 2296, 2301, 2307]
    reason: "Division guarded by early-exit checks in the function"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [2396, 2403, 2421]
    reason: "Cost calculation - guarded by non-zero input validation"

  - file: "streamlit_app/components/ai_workspace.py"
    lines: [2753, 3024, 3053, 3215, 3835, 4202, 4628]
    reason: "Division guarded by loop conditions or input validation"

  # KeyError false positives - DataFrame column assignments to self
  - file: "streamlit_app/components/ai_workspace.py"
    lines: [255, 259, 261, 264, 266, 269, 273, 277, 281, 284, 288, 292, 294, 305, 337, 338, 339]
    reason: "DataFrame column access on result DF being built - columns guaranteed to exist"

  # Lazy imports - intentional for reducing page load time
  - file: "streamlit_app/components/ai_workspace.py"
    lines: [3816, 3839, 3971]
    reason: "Lazy imports in rarely-executed code paths - intentional to reduce initial load"

  # Config dictionary access - config is validated before use
  - file: "streamlit_app/components/ai_workspace.py"
    lines: [2530, 2543, 4413, 4420]
    reason: "Config dict access - config is built with all required keys before this point"

known_issues:
  - file: "streamlit_app/pages/06_游늻_dxf_export.py"
    lines: [222]
    severity: "CRITICAL"
    action: "Fix in next session - undefined color/linetype variables"
