name: ❓ Support / Question
description: Ask a question or request help using the library
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Need help with the library? We're happy to assist!

        **Quick resources:**
        - [Documentation](https://github.com/Pravin-surawase/structural_engineering_lib/tree/main/docs)
        - [API Reference](https://github.com/Pravin-surawase/structural_engineering_lib/blob/main/docs/reference/api.md)
        - [Examples](https://github.com/Pravin-surawase/structural_engineering_lib/tree/main/Python/examples)

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: How do I design a T-beam with the library?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which part of the library is this about?
      options:
        - Python library (structural_lib)
        - Excel/VBA
        - Streamlit app
        - CLI tool
        - DXF export
        - Installation / Setup
        - General usage
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What I tried
      description: What have you already tried?
      placeholder: |
        I tried using api.design_beam_is456() but got an error...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Your environment and what you're trying to achieve
      value: |
        - Library version: [e.g., 0.17.0]
        - Python version: [e.g., 3.11.8]
        - OS: [e.g., Windows 11]
        - Use case: [e.g., beam design for residential building]
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Relevant Output / Errors
      description: Any error messages or unexpected output
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues
          required: true
