<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><IsTestProject>true</IsTestProject><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup><ItemGroup><ProjectReference Include="../../src/StructuralEngineering.Beam/StructuralEngineering.Beam.csproj" /><ProjectReference Include="../../src/StructuralEngineering.Analysis/StructuralEngineering.Analysis.csproj" /><ProjectReference Include="../../src/StructuralEngineering.Construction/StructuralEngineering.Construction.csproj" /><ProjectReference Include="../../src/StructuralEngineering.Reporting/StructuralEngineering.Reporting.csproj" /><ProjectReference Include="../../src/StructuralEngineering.Optimization/StructuralEngineering.Optimization.csproj" /><PackageReference Include="xunit.v3" /></ItemGroup></Project>
