#!/usr/bin/env python3
"""Read-only, worktree-bound startup diagnostics for Windows and POSIX.

Use ./scripts/python_runtime.sh scripts/preflight.py --environment-only --json
for Git, source binding and active-hook proof without ports or optional apps.
No fetch, installation, Git configuration, application start or file writes.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import platform
import shlex
import socket
import subprocess
import sys
import time
from pathlib import Path

from git_state import collect_repository_state

REPO_ROOT = str(Path(__file__).resolve().parents[1])
PYTHON_RUNTIME = str(Path(REPO_ROOT) / "scripts/python_runtime.sh")
REACT_INSTALL_COMMAND = (
    "./scripts/python_runtime.sh scripts/node_runtime.py -- npm --prefix react_app ci"
)
REACT_REQUIRED_TOOLS = ("eslint", "tsc", "vite", "vitest")


def _run(cmd: list[str]) -> tuple[int, str]:
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=REPO_ROOT,
            timeout=10,
            check=False,
            env={**os.environ, "GIT_OPTIONAL_LOCKS": "0", "GIT_TERMINAL_PROMPT": "0"},
        )
        return (
            result.returncode,
            (result.stdout if result.returncode == 0 else result.stderr).strip(),
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return 1, str(exc)


def python_binding() -> dict:
    """Check the interpreter already selected by python_runtime.sh; no shell spawn."""
    try:
        module = importlib.import_module("structural_lib")
        source = Path(module.__file__).resolve()
        bound = source.is_relative_to(Path(REPO_ROOT) / "Python/structural_lib")
        return {
            "status": "PASS" if bound else "FAIL",
            "source_bound": bound,
            "module": str(source),
            "interpreter": sys.executable,
            "version": platform.python_version(),
            "detail": (
                "Python source binding: current worktree"
                if bound
                else "Python source shadowing detected"
            ),
        }
    except (ImportError, OSError, TypeError) as exc:
        return {"status": "FAIL", "source_bound": False, "detail": str(exc)}


def hook_readiness() -> dict:
    """Respect Git's effective hook path; never install/replace an unknown hook."""
    rc, output = _run(
        ["git", "rev-parse", "--path-format=absolute", "--git-path", "hooks/pre-commit"]
    )
    if rc:
        return {
            "status": "FAIL",
            "detail": "Cannot resolve effective pre-commit hook: " + output,
        }
    path = Path(output)
    if not path.is_absolute():
        path = Path(REPO_ROOT) / path
    hint = "Inspect existing configuration; install only if absent: ./scripts/python_runtime.sh -m pre_commit install"
    if not path.is_file():
        return {
            "status": "FAIL",
            "path": str(path),
            "detail": "Active pre-commit hook missing",
            "action": hint,
        }
    try:
        text = path.read_text(encoding="utf-8")
        assignments = [
            line.partition("=")[2]
            for line in text.splitlines()
            if line.startswith("INSTALL_PYTHON=")
        ]
        interpreter = shlex.split(assignments[0])[0] if len(assignments) == 1 else ""
    except (OSError, UnicodeError, ValueError, IndexError) as exc:
        return {
            "status": "FAIL",
            "path": str(path),
            "detail": "Unreadable hook: " + str(exc),
        }
    if (
        "File generated by pre-commit:" not in text
        or "hook-impl" not in text
        or not interpreter
    ):
        return {
            "status": "FAIL",
            "path": str(path),
            "detail": "Custom/unrecognized hook: inspect; do not overwrite",
        }
    if not os.access(path, os.X_OK) or not Path(interpreter).is_file():
        return {
            "status": "FAIL",
            "path": str(path),
            "detail": "Hook or bound interpreter is not executable/available",
        }
    rc, detail = _run([interpreter, "-c", "import pre_commit"])
    return {
        "status": "PASS" if rc == 0 else "FAIL",
        "path": str(path),
        "interpreter": interpreter,
        "detail": (
            "Standard pre-commit hook and interpreter ready" if rc == 0 else detail
        ),
    }


def missing_react_dependencies(repo_root: Path | None = None) -> list[str]:
    root = repo_root or Path(REPO_ROOT)
    bin_dir = root / "react_app/node_modules/.bin"
    return [
        name
        for name in REACT_REQUIRED_TOOLS
        if not (bin_dir / name).exists() and not (bin_dir / f"{name}.cmd").exists()
    ]


def collect_readiness(
    *, environment_only: bool = False, expected_root: Path | None = None
) -> dict:
    started = time.monotonic()
    root = Path(REPO_ROOT).resolve()
    state = collect_repository_state(root, timeout=5)
    checks = {}
    if expected_root is not None:
        checks["requested_worktree"] = {
            "status": "PASS" if expected_root.resolve() == root else "FAIL",
            "detail": f"requested={expected_root.resolve()}; actual={root}",
        }
    git_status = (
        "PASS"
        if state.ready_local
        else "WARN" if state.derived_action == "HOLD_DIRTY" else "FAIL"
    )
    checks["git"] = {
        "status": git_status,
        "detail": state.derived_action,
        "action": "Inspect dirty/held state; no automatic recovery or cross-device synchronization",
    }
    checks["python"] = python_binding()
    checks["hook"] = hook_readiness()
    critical = (
        "run.sh",
        "Python/structural_lib/services/api.py",
        "Python/structural_lib/__init__.py",
        "fastapi_app/main.py",
        "react_app/package.json",
        "docs/git-automation/git-workflow-single-source.md",
    )
    missing_files = [name for name in critical if not (root / name).is_file()]
    checks["key_files"] = {
        "status": "FAIL" if missing_files else "PASS",
        "missing": missing_files,
    }
    if not environment_only:
        missing = missing_react_dependencies()
        checks["react_dependencies"] = {
            "status": "WARN" if missing else "PASS",
            "missing": missing,
            "action": REACT_INSTALL_COMMAND,
        }
        for port, name in ((8000, "FastAPI"), (5173, "React")):
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
                sock.settimeout(1)
                busy = sock.connect_ex(("127.0.0.1", port)) == 0
            checks[f"port_{port}"] = {
                "status": "WARN" if busy else "PASS",
                "detail": f"{name}: {'in use; inspect owner, do not kill' if busy else 'available'}",
            }
    statuses = {row["status"] for row in checks.values()}
    return {
        "schema_version": 1,
        "repository": str(root),
        "host": platform.node(),
        "platform": platform.system(),
        "status": (
            "FAIL" if "FAIL" in statuses else "WARN" if "WARN" in statuses else "PASS"
        ),
        "checks": checks,
        "git_state": state.to_dict(),
        "remote_and_other_device": "NOT_CHECKED",
        "mutation_policy": "READ_ONLY",
        "duration_seconds": round(time.monotonic() - started, 4),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--environment-only", action="store_true")
    parser.add_argument("--expected-root", type=Path)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    report = collect_readiness(
        environment_only=args.environment_only, expected_root=args.expected_root
    )
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(
            f"Read-only preflight: {report['status']} ({report['duration_seconds']:.2f}s)"
        )
        for name, row in report["checks"].items():
            print(
                f"  {row['status']} {name}: {row.get('detail', row.get('missing', ''))}"
            )
            if row["status"] != "PASS" and row.get("action"):
                print(f"    {row['action']}")
        print(
            "  Other device and remote freshness: NOT_CHECKED; fetch/inspect through Codex before writes."
        )
    return 1 if report["status"] == "FAIL" else 0


if __name__ == "__main__":
    raise SystemExit(main())
