namespace StructuralEngineering.Contracts;

public enum AnalysisMode { FixedActions, CoupledReanalysis }
public enum CandidateObjectiveKind { Cost, SteelMass, SectionDepth, Carbon, ConcreteVolume, FormworkArea, Congestion, UtilizationReserve }
public enum CandidateTieBreaker { LowerUtilization, FewerBarMarks, LowerSectionDepth, CandidateId }
public enum CandidateChangeCategory { ActualBars, Detailing, BarPaths, Bbs, RatesCost, ReportOptions, SectionDimensionsProperty, MaterialStiffness, Releases, Offsets, MassSelfWeight, AppliedLoad, LoadCaseCombination, SupportRestraint, Meshing, AnalysisSettings, Unknown }
public enum CandidateCouplingClass { FixedAction, ReanalysisRequired, Unresolved }
public enum SearchStopReason { Completed, EvaluationBudgetReached, Cancelled }
public enum SearchTerminalState { CompleteEnumeration, BudgetExhaustedIncomplete, CancelledIncomplete, EvidenceIncomplete, NoFeasibleCandidate }
public enum CandidateDisposition { Feasible, EngineeringFail, Incomplete, NotEvaluated, DuplicatePhysicalDefinition }

public sealed record CandidateResultBinding(string OperationSemanticId, string ResultId, string NormalizedInputId, string CalculationId, ExecutionState Execution, ApplicabilityState Applicability, EngineeringState Engineering, CompletenessState Completeness, FreshnessState Freshness, string OutputPayloadId);
public sealed record CandidateObjectiveProfile(string ProfileId, string RevisionId, IReadOnlyList<CandidateObjectiveKind> Objectives, IReadOnlyList<CandidateTieBreaker> TieBreakers);
public sealed record SectionCandidateChoice(string ChoiceId, double WidthMm, double OverallDepthMm, double ConcreteStrengthNPerMm2, IReadOnlyList<CandidateChangeCategory>? AdditionalChangeCategories = null);
public sealed record LongitudinalCandidateChoice(string ChoiceId, int TopBarCount, double TopBarDiameterMm, int TopLayerCount, int BottomBarCount, double BottomBarDiameterMm, int BottomLayerCount, double SteelGradeNPerMm2);
public sealed record TransverseCandidateChoice(string ChoiceId, double LinkDiameterMm, double SteelGradeNPerMm2, int Legs, double SpacingMm);
public sealed record DiscreteCandidateDomain(string DomainId, string RevisionId, string ProjectBasisId, string ProfileRevisionId, string MemberId, string TopologyRevisionId, string ActionRevisionId, string DesignScopeRevisionId, string BaselineAnalysisRevisionId, string BaselineSectionChoiceId, IReadOnlyList<SectionCandidateChoice> SectionChoices, IReadOnlyList<LongitudinalCandidateChoice> LongitudinalChoices, IReadOnlyList<TransverseCandidateChoice> TransverseChoices, int MaximumDomainCandidates, IReadOnlyList<string> SourceReferences, IReadOnlyList<string> Limitations);
public sealed record CandidatePhysicalDefinition(double WidthMm, double OverallDepthMm, double ConcreteStrengthNPerMm2, int TopBarCount, double TopBarDiameterMm, int TopLayerCount, int BottomBarCount, double BottomBarDiameterMm, int BottomLayerCount, double LongitudinalSteelGradeNPerMm2, double LinkDiameterMm, double LinkSteelGradeNPerMm2, int LinkLegs, double LinkSpacingMm);
public sealed record BeamCandidateDefinition(string CandidateId, string PhysicalDefinitionId, string DomainId, string DomainRevisionId, SectionCandidateChoice Section, LongitudinalCandidateChoice Longitudinal, TransverseCandidateChoice Transverse, CandidatePhysicalDefinition Physical, IReadOnlyList<CandidateChangeCategory> ChangeCategories, CandidateCouplingClass CouplingClass);
public sealed record CandidateDomainOutput(string DomainId, string DomainRevisionId, string DomainSemanticId, string ProjectBasisId, string ProfileRevisionId, string MemberId, string TopologyRevisionId, string ActionRevisionId, string DesignScopeRevisionId, string BaselineAnalysisRevisionId, string BaselineSectionChoiceId, string TraversalOrder, IReadOnlyList<BeamCandidateDefinition> Candidates, int GeneratedCount);
public sealed record CandidateRankingContext(string ProjectBasisId, string ProfileRevisionId, string MemberId, string TopologyRevisionId, string ActionRevisionId, string DesignScopeRevisionId, string BaselineAnalysisRevisionId, string ReferenceMemberResultId, CandidateResultBinding ReferenceMemberBinding, MemberDesignOutput ReferenceMember);
public sealed record ReanalysisPolicy(string PolicyId, string RevisionId, bool OwnedCopyRequired, string SourceReference);
public sealed record CandidateReanalysisEvidence(string CandidateId, string CandidateDefinitionId, string BaselineAnalysisRevisionId, string CandidateAnalysisRevisionId, string SnapshotResultId, string SnapshotOutputPayloadId, bool ExecutionCompleted, bool FreshnessCurrent);
public sealed record CandidateEvaluation(string CandidateId, string AnalysisRevisionId, CandidateResultBinding MemberBinding, MemberDesignOutput MemberResult, CandidateResultBinding QuantityBinding, ConstructionQuantityOutput Quantities, CandidateResultBinding? CostBinding = null, ConstructionCostOutput? Cost = null, double? EmbodiedCarbonKgCo2e = null, string? CarbonBasisId = null, double? CongestionScore = null, string? CongestionBasisId = null, CandidateReanalysisEvidence? ReanalysisEvidence = null);
public sealed record ObjectiveMetric(CandidateObjectiveKind Kind, double Value, string Unit, string SourceIdentity);
public sealed record RankedCandidate(int Rank, string CandidateId, string PhysicalDefinitionId, CandidateCouplingClass CouplingClass, string AnalysisRevisionId, string MemberResultId, string QuantityResultId, string? CostResultId, IReadOnlyList<ObjectiveMetric> ObjectiveMetrics);
public sealed record CandidateExclusion(string CandidateId, CandidateDisposition Disposition, IReadOnlyList<string> ReasonCodes, string? MemberResultId);
public sealed record CandidateEvaluationRecord(string CandidateId, string PhysicalDefinitionId, CandidateDisposition Disposition, string? AnalysisRevisionId, CandidateResultBinding? MemberBinding, CandidateResultBinding? QuantityBinding, CandidateResultBinding? CostBinding, IReadOnlyList<ObjectiveMetric> ObjectiveMetrics, IReadOnlyList<string> ReasonCodes);
public sealed record SearchPerformance(int DomainCandidateCount, int UniquePhysicalCandidateCount, int DuplicatePhysicalCandidateCount, int EvaluationBudget, int EvaluatedCount, int FeasibleCount, int EngineeringFailCount, int IncompleteCount);
public sealed record CandidateRankingRequest(string RankingId, CandidateRankingContext Context, CandidateDomainOutput Domain, CandidateObjectiveProfile ObjectiveProfile, AnalysisMode AnalysisMode, ReanalysisPolicy? ReanalysisPolicy, int EvaluationBudget, SearchStopReason StopReason, IReadOnlyList<CandidateEvaluation> Evaluations);
public sealed record CandidateRankingOutput(string RankingId, string DomainId, string DomainSemanticId, string ExpectedLeafSetId, AnalysisMode AnalysisMode, string BaselineAnalysisRevisionId, string ObjectiveProfileId, string ObjectiveProfileRevisionId, IReadOnlyList<CandidateTieBreaker> EffectiveTieBreakers, IReadOnlyList<CandidateEvaluationRecord> EvaluationRecords, IReadOnlyList<RankedCandidate> RankedCandidates, IReadOnlyList<CandidateExclusion> Exclusions, SearchPerformance Performance, SearchTerminalState TerminalState, bool EnumerationComplete, string? BestEvaluatedCandidateId, string? SelectedCandidateId, bool OptimalityClaimed, bool InfeasibleClaimed, bool ProvisionalShortlist, string OptimalityScope);
public sealed record BeamOptimizationRequest(string SearchId, CandidateRankingContext Context, DiscreteCandidateDomain Domain, CandidateObjectiveProfile ObjectiveProfile, AnalysisMode AnalysisMode, ReanalysisPolicy? ReanalysisPolicy, int EvaluationBudget, SearchStopReason StopReason, IReadOnlyList<CandidateEvaluation> Evaluations);
public sealed record BeamOptimizationOutput(string SearchId, CandidateDomainOutput Domain, CandidateRankingOutput Ranking);
