"""Portable read-only startup regression tests; no apps or real Git mutation."""

from __future__ import annotations

import importlib
import shlex
import sys
from pathlib import Path, PurePosixPath, PureWindowsPath
from types import SimpleNamespace

import pytest

pytestmark = pytest.mark.repo_only
SCRIPTS = Path(__file__).resolve().parents[2] / "scripts"
sys.path.insert(0, str(SCRIPTS))
preflight = importlib.import_module("preflight")


@pytest.fixture
def ready(monkeypatch):
    # The semantic state itself is owned/tested by git_state.py. This fixture
    # exercises the startup consumer, including failed query propagation.
    state = SimpleNamespace(
        ready_local=True,
        derived_action="READY_LOCAL",
        to_dict=lambda: {"derived_action": "READY_LOCAL"},
    )
    monkeypatch.setattr(preflight, "collect_repository_state", lambda *_a, **_k: state)
    monkeypatch.setattr(
        preflight, "python_binding", lambda: {"status": "PASS", "source_bound": True}
    )
    monkeypatch.setattr(preflight, "hook_readiness", lambda: {"status": "PASS"})
    return state


@pytest.mark.parametrize(
    "action",
    [
        "HOLD_UNKNOWN",
        "HOLD_OPERATION",
        "HOLD_LOCKED",
        "HOLD_BEHIND",
        "HOLD_DIVERGED",
        "HOLD_MAIN",
        "HOLD_DETACHED",
    ],
)
def test_unsafe_or_failed_git_queries_never_report_ready(ready, action):
    ready.ready_local = False
    ready.derived_action = action
    assert preflight.collect_readiness(environment_only=True)["status"] == "FAIL"


def test_clean_synchronized_main_is_admitted_only_for_read_only_intake(ready):
    ready.ready_local = False
    ready.derived_action = "HOLD_MAIN"
    ready.tree = SimpleNamespace(clean=True)
    ready.operation = "none"
    ready.locks = []
    ready.default_base = SimpleNamespace(status="equal")

    result = preflight.collect_readiness(
        environment_only=True, allow_clean_main_intake=True
    )

    assert result["status"] == "PASS"
    assert result["checks"]["git"]["detail"] == "HOLD_MAIN_INTAKE_ONLY"


def test_dirty_state_is_visible_warning_not_mutation_authority(ready):
    ready.ready_local = False
    ready.derived_action = "HOLD_DIRTY"
    result = preflight.collect_readiness(environment_only=True)
    assert result["status"] == "WARN"
    assert result["mutation_policy"] == "READ_ONLY"
    assert result["remote_and_other_device"] == "NOT_CHECKED"


def test_requested_worktree_mismatch_blocks(ready, tmp_path):
    assert (
        preflight.collect_readiness(environment_only=True, expected_root=tmp_path)[
            "status"
        ]
        == "FAIL"
    )


def test_environment_mode_does_not_probe_apps_or_ports(ready, monkeypatch):
    monkeypatch.setattr(
        preflight.socket, "socket", lambda *_a: pytest.fail("unexpected port access")
    )
    monkeypatch.setattr(
        preflight,
        "missing_react_dependencies",
        lambda: pytest.fail("unexpected app dependency probe"),
    )
    assert preflight.collect_readiness(environment_only=True)["status"] == "PASS"


def test_source_binding_checks_current_import_not_installed_version(
    monkeypatch, tmp_path
):
    monkeypatch.setattr(preflight, "REPO_ROOT", str(tmp_path))
    module = SimpleNamespace(
        __file__=str(tmp_path / "Python/structural_lib/__init__.py")
    )
    monkeypatch.setattr(preflight.importlib, "import_module", lambda _name: module)
    assert preflight.python_binding()["source_bound"] is True
    module.__file__ = str(tmp_path / "another-checkout/structural_lib/__init__.py")
    assert preflight.python_binding()["status"] == "FAIL"


def test_hook_absence_is_not_confused_with_installed_package(monkeypatch, tmp_path):
    monkeypatch.setattr(
        preflight, "_run", lambda _cmd: (0, str(tmp_path / "pre-commit"))
    )
    result = preflight.hook_readiness()
    assert result["status"] == "FAIL"
    assert "missing" in result["detail"]
    assert not (tmp_path / "pre-commit").exists()


def test_standard_hook_with_space_path_and_live_interpreter(monkeypatch, tmp_path):
    hook = tmp_path / "hook dir/pre-commit"
    hook.parent.mkdir()
    hook.write_text(
        "#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\nINSTALL_PYTHON="
        + shlex.quote(sys.executable)
        + "\nARGS=(hook-impl)\n",
        encoding="utf-8",
    )
    hook.chmod(0o755)
    calls = []

    def query(cmd):
        calls.append(cmd)
        return (0, str(hook)) if cmd[0] == "git" else (0, "")

    monkeypatch.setattr(preflight, "_run", query)
    assert preflight.hook_readiness()["status"] == "PASS"
    assert calls[-1] == [sys.executable, "-c", "import pre_commit"]
    # We never execute the hook or mutate its contents during a diagnostic.
    assert len(calls) == 4


def test_custom_hook_is_preserved_and_not_executed(monkeypatch, tmp_path):
    hook = tmp_path / "pre-commit"
    content = "#!/bin/sh\necho custom owner hook\n"
    hook.write_text(content, encoding="utf-8")
    monkeypatch.setattr(preflight, "_run", lambda _cmd: (0, str(hook)))
    assert preflight.hook_readiness()["status"] == "FAIL"
    assert hook.read_text(encoding="utf-8") == content


def test_shell_launch_failure_is_structured_not_unhandled(monkeypatch):
    def fail(*_args, **_kwargs):
        raise OSError("not a native executable")

    monkeypatch.setattr(preflight.subprocess, "run", fail)
    code, error = preflight._run(["missing-executable"])
    assert code == 1 and "not a native executable" in error


def test_windows_react_command_shims_are_recognized(tmp_path):
    directory = tmp_path / "react_app/node_modules/.bin"
    directory.mkdir(parents=True)
    for name in preflight.REACT_REQUIRED_TOOLS:
        (directory / f"{name}.cmd").touch()
    assert preflight.missing_react_dependencies(tmp_path) == []


def test_handoff_brief_is_written_as_lf_on_every_host(monkeypatch, tmp_path):
    session = importlib.import_module("scripts.session")
    path = tmp_path / "brief.md"
    path.write_bytes(b"# Brief\r\n\r\nExisting material\r\n")
    monkeypatch.setattr(session, "NEXT_BRIEF", path)
    session._update_next_brief(["- New observation"])
    assert b"\r\n" not in path.read_bytes()
    assert b"Existing material" in path.read_bytes()


def test_handoff_receipt_writer_is_lf(monkeypatch, tmp_path):
    receipt = importlib.import_module("scripts.git_handoff_receipt")
    monkeypatch.setattr(receipt, "collect_repository_state", lambda _repo: None)
    monkeypatch.setattr(receipt, "build_receipt", lambda **_kwargs: {"test": "value"})
    path = tmp_path / "receipt.json"
    assert (
        receipt.main(
            [
                "create",
                "--task-id",
                "TEST",
                "--integration-owner",
                "test",
                "--output",
                str(path),
            ]
        )
        == 0
    )
    assert b"\r\n" not in path.read_bytes()
    assert path.read_bytes().endswith(b"\n")


@pytest.mark.parametrize(
    "path_type,root", [(PureWindowsPath, "C:/repo"), (PurePosixPath, "/repo")]
)
@pytest.mark.parametrize(
    "relative,layer",
    [
        ("Python/structural_lib/core/example.py", "core"),
        ("Python/structural_lib/codes/is456/example.py", "is456"),
        ("fastapi_app/routers/example.py", "ui"),
    ],
)
def test_architecture_layer_detection_is_identical_for_both_path_flavors(
    path_type, root, relative, layer
):
    architecture = importlib.import_module("check_architecture_boundaries")
    base = path_type(root)
    assert architecture.get_layer(base / relative, base) == layer


def test_governance_retained_dates_are_allowed_but_invalid_locations_still_fail(
    monkeypatch, tmp_path
):
    governance = importlib.import_module("check_governance")
    monkeypatch.setattr(governance, "REPO_ROOT", tmp_path)
    archived = tmp_path / "docs/_archive/retained-2026-08-30.md"
    archived.parent.mkdir(parents=True)
    archived.write_text("historical evidence", encoding="utf-8")
    wrong = tmp_path / "bad-2026-08-30.md"
    wrong.write_text("misplaced", encoding="utf-8")
    report = governance.GovernanceReport()
    governance.check_dated_files(report)
    assert len(report.errors) == 1
    assert "bad-2026-08-30.md" in report.errors[0].message


def test_governance_preserves_layer_exceptions_without_hiding_real_violations(
    monkeypatch, tmp_path
):
    governance = importlib.import_module("check_governance")
    monkeypatch.setattr(governance, "REPO_ROOT", tmp_path)
    lib = tmp_path / "Python/structural_lib"
    bad = lib / "core/bad.py"
    allowed = lib / "services/api.py"
    bad.parent.mkdir(parents=True)
    allowed.parent.mkdir(parents=True)
    bad.write_text("import structural_lib.services.api\n", encoding="utf-8")
    allowed.write_text("import structural_lib.insights.sensitivity\n", encoding="utf-8")
    report = governance.GovernanceReport()
    governance.check_python_layer_boundaries(report)
    assert len(report.errors) == 1
    assert len(report.errors[0].files) == 1
    assert "bad.py" in report.errors[0].files[0]
