# SPDX-License-Identifier: MIT
# Copyright (c) 2024-2026 Pravin Surawase
"""
Package:      structural_lib
Description:  IS 456:2000 Structural Engineering Library
License:      MIT

Version is read from the imported source checkout or installed distribution.
Use api.get_library_version() to get the current version.
"""

from __future__ import annotations

import importlib
from types import ModuleType as _ModuleType

from .core.version import get_runtime_version as _get_runtime_version

# Source checkout and installed-wheel modes have different authorities. The
# resolver prevents unrelated installed metadata from relabelling source code.
__version__ = _get_runtime_version(__file__)

# Expose key modules
from . import (
    api,
    compliance,
    design,
    detailing,
    flexure,
    imports,
    inputs,
    models,
    rebar,
    result_base,
    serviceability,
    shear,
    types,
)
from .core.analysis_contracts import (
    AnalysisStateV1,
    AnalysisStatusIdentityV1,
    BeamActionComponentV1,
    BeamActionRowV1,
    BeamDemandEnvelopeModeV1,
    BeamDemandEnvelopeRuleV1,
    BeamDemandPurposeV1,
    BeamDemandScenarioV1,
    BeamDemandSnapshotV1,
    BeamGoverningReferenceV1,
    BeamGoverningSignV1,
    BeamStationDomainV1,
    DeterministicTieBreakV1,
    EvidenceStateV1,
    EvidenceValueV1,
    JointDisplacementRowV1,
    JointReactionRowV1,
    JointResultSourceCountV1,
    LinearStaticCaseParametersV1,
    LinearStaticInitialConditionV1,
    LinearStaticLoadItemV1,
    LoadCaseDefinitionV1,
    LoadCaseParameterSetKindV1,
    LoadPatternDefinitionV1,
    ModelDofRestraintsV1,
    ModelEndOffsetsV1,
    ModelFrameDefinitionV1,
    ModelFrameDistributedLoadV1,
    ModelFramePointLoadV1,
    ModelInsertionPointV1,
    ModelJointDefinitionV1,
    ModelJointLoadV1,
    ModelMaterialV1,
    ModelModifiersV1,
    ModelPointV1,
    ModelReleasesV1,
    ModelSectionV1,
    ModelSpringTermV1,
    ModelSpringV1,
    ResponseCombinationDefinitionV1,
    ResponseCombinationFactorV1,
    ResponseCombinationSourceKindV1,
    ResultSelectionIdentityV1,
    ResultSelectionKindV1,
    UnsupportedCaseParametersV1,
)

# Import W3 contracts after the established services facade has initialized.
from .core.beam_line import (
    BeamLineAnalysisBuildResultV1,
    BeamLineAnalysisRequestV1,
    BeamLineAnalysisResultV1,
    BeamLineCombinationV1,
    BeamLineEquilibriumV1,
    BeamLineFactorV1,
    BeamLineIssueV1,
    BeamLineLoadCaseV1,
    BeamLineNodalLoadV1,
    BeamLineNodeResultV1,
    BeamLineNodeV1,
    BeamLineNumericsV1,
    BeamLinePointLoadV1,
    BeamLineScenarioV1,
    BeamLineSpanResultV1,
    BeamLineSpanV1,
    BeamLineStationV1,
    BeamLineSupportSpringV1,
    BeamLineSupportV1,
    BeamLineUniformLoadV1,
)
from .core.beam_line_calibration import (
    BeamLineActionMappingV1,
    BeamLineCalibrationV1,
    BeamLineComparisonComponentV1,
    BeamLineComparisonCriteriaV1,
    BeamLineComparisonRequestV1,
    BeamLineComponentComparisonV1,
    BeamLineComponentToleranceV1,
    BeamLineJointMappingV1,
    BeamLineReferenceIdentityV1,
    BeamLineReferenceMappingV1,
    BeamLineReferenceV1,
)
from .core.calculation_dossier import (
    AttestedCalculationDossierV1,
    CalculationDossierBuildRequestV1,
    CalculationDossierBuildResultV1,
    CalculationDossierV1,
    DigitalSignatureEvidenceV1,
    DossierArtifactV1,
    DossierIdentityV1,
    DossierIssueV1,
    DossierVerificationResultV1,
    ProfessionalIdentityV1,
    ReviewAttestationV1,
    ReviewScopeV1,
    SignedCalculationDossierV1,
)

# Import EndCondition enum (needed for calculate_effective_length_is456)
from .core.data_types import EndCondition

# Import geometry and frame types from core.models
from .core.models import BeamGeometry, DesignDefaults, FrameType

# Import all public API functions from services.api
from .services.api import (  # Audit & Verification; Input dataclasses; Calculation Report; Self-validation (TASK-724); Return types (for type annotations); Load Analysis; ETABS Integration; Multi-objective optimization; Torsion Design; Column Design; Serviceability; Outputs; Core design functions; Shear; Version; Smart features; Diagnostics (TASK-725); Footing Design (IS 456 Cl 34); Validation
    AuditLogEntry,
    AuditTrail,
    BeamGeometryInput,
    BeamInput,
    BeamReinforcementEvaluationV1,
    BeamReinforcementSelectionConstraintsV1,
    BearingPressureCheckResult,
    BearingStressEnhancementResult,
    BracedWallDesignInput,
    BracedWallDesignProvenance,
    BracedWallDesignResult,
    CalculationHash,
    CalculationReport,
    CheckCodeReport,
    CompleteOneWaySlabDesignResult,
    ComplianceCaseResult,
    ComplianceReport,
    ComposedWorkflowCapability,
    ConcentricIsolatedFootingInput,
    ConcentricIsolatedFootingResult,
    ContinuousOneWaySlabDesignResult,
    CostProfile,
    CriticalPoint,
    DesignAndDetailResult,
    DetailingConfigInput,
    EffectiveDepthBasisV1,
    EffectiveDepthResolutionV1,
    ETABSEnvelopeResult,
    ETABSForceRow,
    FlangedBeamDesignResult,
    FootingBearingResult,
    FootingDepthCandidate,
    FootingDirectionalReinforcementDemand,
    FootingFlexureResult,
    FootingOneWayShearResult,
    FootingProvenance,
    FootingPunchingResult,
    GravityBeamDesignBasisV1,
    GravityBeamReinforcementBasisV1,
    GravityLongitudinalBarLayersV1,
    GravityPracticalActionKindV1,
    GravityPracticalActionReconciliationV1,
    GravityPracticalActionUnitsV1,
    GravityPracticalActionV1,
    GravityWorkflowDefinitionV1,
    GravityWorkflowRequestV1,
    GravityWorkflowResultV1,
    GravityWorkflowRunBundleV1,
    InputSection,
    IS456Capability,
    LoadCaseInput,
    LoadDefinition,
    LoadDiagramResult,
    LoadsInput,
    LoadTransferResult,
    LoadType,
    LongitudinalBarLayersV1,
    MaterialsInput,
    OneWaySlabDesignResult,
    OptimizationConstraints,
    OptimizationInfeasibleError,
    ParetoCandidate,
    ParetoOptimizationResult,
    ProjectInfo,
    PropertyLineStrapFootingDesignInput,
    PropertyLineStrapFootingDesignProvenance,
    PropertyLineStrapFootingDesignResult,
    PropertyLineStrapFootingDesignStatus,
    RectangularGravityWorkflowBuilderInputV1,
    RegularInteriorFlatSlabDesignInput,
    RegularInteriorFlatSlabDesignProvenance,
    RegularInteriorFlatSlabDesignResult,
    RegularInteriorFlatSlabDesignStatus,
    ResultSection,
    SimplySupportedDeepBeamDesignInput,
    SimplySupportedDeepBeamDesignProvenance,
    SimplySupportedDeepBeamDesignResult,
    StraightFlightStaircaseInput,
    StraightFlightStaircaseProvenance,
    StraightFlightStaircaseResult,
    SuppliedBeamReinforcementV1,
    SymmetricCombinedFootingDesignInput,
    SymmetricCombinedFootingDesignProvenance,
    SymmetricCombinedFootingDesignResult,
    SymmetricCombinedFootingDesignStatus,
    TensionBarAnchorageResultV1,
    TorsionResult,
    TwoWaySlabPanelWorkflowResult,
    ValidationReport,
    VersionInfo,
    WorkflowCatalog,
    bearing_stress_enhancement,
    biaxial_bending_check_is456,
    build_detailing_input,
    build_rectangular_gravity_workflow_request_v1,
    calculate_additional_moment_is456,
    calculate_development_length,
    calculate_development_length_unrounded,
    calculate_effective_length_is456,
    calculate_equivalent_moment,
    calculate_equivalent_shear,
    calculate_longitudinal_torsion_steel,
    calculate_torsion_shear_stress,
    calculate_torsion_stirrup_area,
    check_anchorage_at_simple_support,
    check_beam_ductility,
    check_beam_is456,
    check_beam_slenderness,
    check_bearing_pressure,
    check_code,
    check_column_ductility_is13920,
    check_compliance_report,
    check_crack_width,
    check_deflection_span_depth,
    check_helical_reinforcement_is456,
    check_isolated_footing_load_transfer,
    classify_column_is456,
    compute_bbs,
    compute_bmd_sfd,
    compute_critical,
    compute_detailing,
    compute_dxf,
    compute_hash,
    compute_report,
    create_calculation_certificate,
    create_job_from_etabs,
    create_jobs_from_etabs_csv,
    design_and_detail_beam_is456,
    design_beam_is456,
    design_braced_wall_is456,
    design_column_axial_is456,
    design_column_is456,
    design_complete_one_way_slab_is456,
    design_concentric_isolated_footing_is456,
    design_continuous_one_way_slab_builtin_is456,
    design_continuous_one_way_slab_is456,
    design_flanged_beam_is456,
    design_from_input,
    design_long_column_is456,
    design_one_way_slab_is456,
    design_property_line_strap_footing_is456,
    design_regular_interior_flat_slab_is456,
    design_short_column_uniaxial_is456,
    design_simply_supported_deep_beam_is456,
    design_straight_flight_staircase_is456,
    design_symmetric_combined_footing_is456,
    design_torsion,
    design_two_way_slab_is456,
    design_two_way_slab_panel_builtin_is456,
    design_two_way_slab_panel_is456,
    detail_beam_is456,
    detail_column_is456,
    enhanced_shear_strength_is456,
    evaluate_supplied_beam_reinforcement_v1,
    evaluate_tension_bar_anchorage_v1,
    export_bbs,
    footing_flexure,
    footing_one_way_shear,
    footing_punching_shear,
    generate_calculation_report,
    get_gravity_workflow_definition_v1,
    get_gravity_workflow_example_document_v1,
    get_gravity_workflow_example_request_v1,
    get_library_version,
    get_supported_is456_capabilities,
    get_supported_is456_capability_document,
    get_supported_is456_semantic_contract,
    get_workflow_catalog,
    get_workflow_catalog_document,
    load_etabs_csv,
    min_eccentricity_is456,
    normalize_etabs_forces,
    optimize_beam_cost,
    optimize_pareto_front,
    pm_interaction_curve_is456,
    run_gravity_workflow_v1,
    run_gravity_workflow_with_book_v1,
    serialize_workflow_catalog,
    show_versions,
    size_footing,
    smart_analyze_design,
    suggest_beam_design_improvements,
    validate_design_results,
    validate_etabs_csv,
    validate_job_spec,
    verify_calculation,
)
from .services.beam_audit import (
    BeamAuditApplicabilityBasisV1,
    BeamAuditCheckV1,
    BeamAuditEvaluationRequestV1,
    BeamAuditEvaluationResultV1,
    BeamAuditInputBuildRequestV1,
    BeamAuditInputBuildResultV1,
    BeamAuditInputsV1,
    BeamAuditMemberBasisV1,
    BeamAuditRowEvaluationRequestV1,
    BeamAuditRowEvaluationResultV1,
    BeamAuditRowInputV1,
    BeamAuditRowResultV1,
    build_beam_audit_inputs_v1,
    canonical_beam_action_row_sha256_v1,
    evaluate_beam_audit_row_v1,
    evaluate_beam_audit_v1,
)
from .services.beam_candidate_evaluator import (
    BeamCandidateCheckEvidenceV2,
    BeamCandidateCheckResultV2,
    BeamCandidateCompositionV2,
    BeamCandidateDefinitionDraftV2,
    BeamCandidateDefinitionV2,
    BeamCandidateEvaluationResultV2,
    build_beam_candidate_definition_v2,
    check_beam_candidate_composition_v2,
    evaluate_beam_candidate_v2,
)
from .services.beam_candidate_search import (
    BeamCandidateProjectionV1,
    BeamCandidateSearchDomainDraftV1,
    BeamCandidateSearchDomainV1,
    BeamCandidateSearchRequestV1,
    BeamCandidateSearchResultV1,
    OptimizationSearchBudgetV1,
    build_beam_candidate_search_domain_v1,
    search_beam_candidates_v1,
)
from .services.beam_line import solve_beam_line_linear_v1
from .services.beam_line_calibration import compare_beam_line_to_reference_v1
from .services.beam_project_contracts import (
    BeamCriteriaScenarioV1,
    BeamCriteriaStopPolicyV1,
    BeamExistingPropertyDraftV1,
    BeamExistingPropertyV1,
    BeamLongitudinalLayerV1,
    BeamLongitudinalStockV1,
    BeamMemberReinforcementScheduleDraftV1,
    BeamMemberReinforcementScheduleV1,
    BeamPropertyCostBasisV1,
    BeamTransverseStockV1,
    BeamTransverseZoneV1,
    ProjectBeamCandidateCatalogueDraftV1,
    ProjectBeamCandidateCatalogueV1,
    ProjectBeamCriteriaDraftV1,
    ProjectBeamCriteriaV1,
    build_beam_existing_property_v1,
    build_beam_member_reinforcement_schedule_v1,
    build_project_beam_candidate_catalogue_v1,
    build_project_beam_criteria_v1,
)
from .services.calculation_dossier import (
    attach_digital_signature_evidence_v1,
    build_calculation_dossier_v1,
    record_review_attestation_v1,
    verify_signed_calculation_dossier_v1,
)
from .services.contracts.etabs_w3 import (
    BeamActionPageV1,
    BeamDemandBuildResultV1,
    BeamDemandDerivationRequestV1,
    ETABSDisplacementBuildRequestV1,
    ETABSDisplacementBuildResultV1,
    ETABSDisplacementSnapshotV1,
    ETABSModelContextV1,
    ETABSModelDefinitionBuildRequestV1,
    ETABSModelDefinitionBuildResultV1,
    ETABSModelDefinitionSnapshotV1,
    ETABSOutputSelectionStateV1,
    ETABSReactionBuildRequestV1,
    ETABSReactionBuildResultV1,
    ETABSReactionSnapshotV1,
    ETABSResultCatalogueBuildRequestV1,
    ETABSResultCatalogueBuildResultV1,
    ETABSResultCatalogueCapacityV1,
    ETABSResultCatalogueV1,
    W3BuildIssueV1,
    W3BuildStatusV1,
    build_etabs_displacement_snapshot_v1,
    build_etabs_model_definition_snapshot_v1,
    build_etabs_reaction_snapshot_v1,
    build_etabs_result_catalogue_v1,
    canonical_beam_demand_snapshot_hash_basis_json_v1,
    canonical_etabs_result_catalogue_hash_basis_json_v1,
    derive_beam_demand_snapshot_v1,
    query_beam_action_rows_v1,
    verify_beam_demand_snapshot_hash_v1,
    verify_etabs_displacement_snapshot_hash_v1,
    verify_etabs_model_definition_snapshot_hash_v1,
    verify_etabs_reaction_snapshot_hash_v1,
    verify_etabs_result_catalogue_hash_v1,
)
from .services.etabs_acquisition_contracts import (
    ETABSConcreteDesignBasisDraftV1,
    ETABSConcreteDesignBasisV1,
    ETABSDesignSettingV1,
    ETABSExportBoundsV1,
    ETABSInstalledSQLiteEvidenceV1,
    ETABSRequestedTableV1,
    ETABSSQLiteColumnInventoryV1,
    ETABSSQLiteExportManifestDraftV1,
    ETABSSQLiteExportManifestV1,
    ETABSSQLiteRequestedFieldResolutionV1,
    ETABSSQLiteRequestedTableResolutionV1,
    ETABSSQLiteSchemaInventoryV1,
    ETABSSQLiteTableInventoryV1,
    build_etabs_installed_sqlite_evidence_v1,
    build_etabs_concrete_design_basis_v1,
    finalize_etabs_sqlite_export_manifest_v1,
    inventory_etabs_sqlite_export_v1,
)
from .services.etabs_catalogue_bridge import (
    ETABSLiveCaseStatusV1,
    ETABSLiveCatalogueRunRequestV1,
    ETABSLiveCatalogueStateV1,
    ETABSLiveCatalogueTransportV1,
    ETABSLiveSelectionStateV1,
    run_etabs_live_catalogue_v1,
)
from .services.etabs_installed_readonly import (
    ETABSInstalledReadOnlyCaptureV1,
    ETABSInstalledReadOnlyReaderV1,
    ETABSInstalledReadOnlyRunV1,
    capture_etabs_installed_readonly_v1,
    etabs_state_content_sha256_v1,
    run_etabs_installed_readonly_v1,
)
from .services.etabs_operation_control import (
    ETABSArtifactIdentityV1,
    ETABSBrokerResultV1,
    ETABSCallLedgerIdentityV1,
    ETABSCallLedgerV1,
    ETABSCallRecordV1,
    ETABSEvidenceBundleV1,
    ETABSLeaseHandleV1,
    ETABSOperationLeaseV1,
    ETABSOperationOutcomeV1,
    acquire_etabs_operation_lease_v1,
    build_etabs_operation_outcome_v1,
    finalize_etabs_evidence_bundle_v1,
    invoke_recorded_etabs_call_v1,
    run_etabs_sta_broker_v1,
    verify_etabs_call_ledger_v1,
    verify_etabs_evidence_bundle_v1,
)
from .services.etabs_result_catalogue_adapter import (
    ETABSCatalogueAdapterRequestV1,
    ETABSCatalogueAdapterResultV1,
    ETABSCatalogueSelectionRequestV1,
    ETABSGetterCallEvidenceV1,
    ETABSGetterContainerKindV1,
    ETABSGetterOutcomeV1,
    extract_etabs_result_catalogue_v1,
)
from .services.etabs_session_guard import (
    ETABSAccessModeV1,
    ETABSAttachedStateReaderV1,
    ETABSBridgeCapabilityV1,
    ETABSExpectedModelIntentV1,
    ETABSFileIdentityV1,
    ETABSInstalledReadOnlyPreflightV1,
    ETABSModelFreshnessDispositionV1,
    ETABSModelFreshnessV1,
    ETABSProcessInstanceV1,
    ETABSResultEpochDispositionV1,
    ETABSResultEpochV1,
    ETABSRuntimeArtifactV1,
    ETABSRuntimeFingerprintV1,
    ETABSSavedCheckpointV1,
    ETABSSessionIdentityV1,
    ETABSStateSnapshotV1,
    ETABSTargetObservationV1,
    ProcessObservationV1,
    assess_attached_output_readiness_v1,
    build_etabs_result_epoch_v1,
    build_etabs_runtime_fingerprint_v1,
    build_etabs_saved_checkpoint_v1,
    build_etabs_session_identity_v1,
    capture_attached_etabs_state_v1,
    capture_etabs_state_v1,
    classify_etabs_model_freshness_v1,
    compare_attached_etabs_state_v1,
    discover_etabs_processes_v1,
    file_identity_v1,
    issue_etabs_bridge_capability_v1,
    observe_etabs_target_v1,
    preflight_installed_etabs_readonly_v1,
    verify_etabs_bridge_capability_v1,
    verify_etabs_target_observation_v1,
)

# Import 3D visualization from visualization.geometry_3d
from .visualization.geometry_3d import (
    Beam3DGeometry,
    Point3D,
    RebarPath,
    RebarSegment,
    StirrupLoop,
    beam_to_3d_geometry,
    compute_beam_outline,
    compute_rebar_positions,
    compute_stirrup_path,
    compute_stirrup_positions,
)

# Lazy-loaded modules (imported on first access, not at package load)
_LAZY_MODULES = {
    "adapters",
    "etabs_import",
    "batch",
    "costing",
    "testing_strategies",
    "audit",
    "serialization",
}

# DXF export is optional (requires ezdxf)
dxf_export: _ModuleType | None
try:
    dxf_export = importlib.import_module(f"{__name__}.services.dxf_export")
except ImportError:
    dxf_export = None

# Reports module is optional (requires jinja2)
reports: _ModuleType | None
try:
    reports = importlib.import_module(f"{__name__}.reports")
except ImportError:
    reports = None

__all__ = [
    "AttestedCalculationDossierV1",
    "CalculationDossierBuildRequestV1",
    "CalculationDossierBuildResultV1",
    "CalculationDossierV1",
    "DigitalSignatureEvidenceV1",
    "DossierArtifactV1",
    "DossierIdentityV1",
    "DossierIssueV1",
    "DossierVerificationResultV1",
    "ProfessionalIdentityV1",
    "ReviewAttestationV1",
    "ReviewScopeV1",
    "SignedCalculationDossierV1",
    "attach_digital_signature_evidence_v1",
    "build_calculation_dossier_v1",
    "record_review_attestation_v1",
    "verify_signed_calculation_dossier_v1",
    "BeamLineNodeV1",
    "BeamLineSpanV1",
    "BeamLineSupportV1",
    "BeamLineSupportSpringV1",
    "BeamLineUniformLoadV1",
    "BeamLinePointLoadV1",
    "BeamLineNodalLoadV1",
    "BeamLineLoadCaseV1",
    "BeamLineFactorV1",
    "BeamLineCombinationV1",
    "BeamLineScenarioV1",
    "BeamLineNumericsV1",
    "BeamLineAnalysisRequestV1",
    "BeamLineNodeResultV1",
    "BeamLineStationV1",
    "BeamLineSpanResultV1",
    "BeamLineEquilibriumV1",
    "BeamLineAnalysisResultV1",
    "BeamLineIssueV1",
    "BeamLineAnalysisBuildResultV1",
    "solve_beam_line_linear_v1",
    "BeamLineActionMappingV1",
    "BeamLineCalibrationV1",
    "BeamLineComparisonComponentV1",
    "BeamLineComparisonCriteriaV1",
    "BeamLineComparisonRequestV1",
    "BeamLineComponentComparisonV1",
    "BeamLineComponentToleranceV1",
    "BeamLineJointMappingV1",
    "BeamLineReferenceIdentityV1",
    "BeamLineReferenceMappingV1",
    "BeamLineReferenceV1",
    "compare_beam_line_to_reference_v1",
    "ModelJointLoadV1",
    "JointResultSourceCountV1",
    "JointDisplacementRowV1",
    "JointReactionRowV1",
    "ModelDofRestraintsV1",
    "ModelEndOffsetsV1",
    "ModelFrameDefinitionV1",
    "ModelFrameDistributedLoadV1",
    "ModelFramePointLoadV1",
    "ModelInsertionPointV1",
    "ModelJointDefinitionV1",
    "ModelMaterialV1",
    "ModelModifiersV1",
    "ModelPointV1",
    "ModelReleasesV1",
    "ModelSectionV1",
    "ModelSpringTermV1",
    "ModelSpringV1",
    "ETABSModelContextV1",
    "ETABSOutputSelectionStateV1",
    "ETABSModelDefinitionBuildRequestV1",
    "ETABSModelDefinitionBuildResultV1",
    "ETABSModelDefinitionSnapshotV1",
    "ETABSDisplacementBuildRequestV1",
    "ETABSDisplacementBuildResultV1",
    "ETABSDisplacementSnapshotV1",
    "ETABSReactionBuildRequestV1",
    "ETABSReactionBuildResultV1",
    "ETABSReactionSnapshotV1",
    "build_etabs_model_definition_snapshot_v1",
    "build_etabs_displacement_snapshot_v1",
    "build_etabs_reaction_snapshot_v1",
    "verify_etabs_model_definition_snapshot_hash_v1",
    "verify_etabs_displacement_snapshot_hash_v1",
    "verify_etabs_reaction_snapshot_hash_v1",
    "__version__",
    # W3 analysis, evidence, catalogue, and demand contracts
    "AnalysisStateV1",
    "AnalysisStatusIdentityV1",
    "BeamActionComponentV1",
    "BeamActionPageV1",
    "BeamActionRowV1",
    "BeamDemandBuildResultV1",
    "BeamDemandDerivationRequestV1",
    "BeamDemandEnvelopeModeV1",
    "BeamDemandEnvelopeRuleV1",
    "BeamDemandPurposeV1",
    "BeamDemandScenarioV1",
    "BeamDemandSnapshotV1",
    "BeamGoverningReferenceV1",
    "BeamGoverningSignV1",
    "BeamStationDomainV1",
    "DeterministicTieBreakV1",
    "ETABSCatalogueAdapterRequestV1",
    "ETABSCatalogueAdapterResultV1",
    "ETABSCatalogueSelectionRequestV1",
    "ETABSGetterCallEvidenceV1",
    "ETABSGetterContainerKindV1",
    "ETABSGetterOutcomeV1",
    "ETABSLiveCaseStatusV1",
    "ETABSLiveCatalogueRunRequestV1",
    "ETABSLiveCatalogueStateV1",
    "ETABSLiveCatalogueTransportV1",
    "ETABSLiveSelectionStateV1",
    "ETABSResultCatalogueBuildRequestV1",
    "ETABSResultCatalogueBuildResultV1",
    "ETABSResultCatalogueCapacityV1",
    "ETABSResultCatalogueV1",
    "EvidenceStateV1",
    "EvidenceValueV1",
    "LinearStaticCaseParametersV1",
    "LinearStaticInitialConditionV1",
    "LinearStaticLoadItemV1",
    "LoadCaseDefinitionV1",
    "LoadCaseParameterSetKindV1",
    "LoadPatternDefinitionV1",
    "ResponseCombinationDefinitionV1",
    "ResponseCombinationFactorV1",
    "ResponseCombinationSourceKindV1",
    "ResultSelectionIdentityV1",
    "ResultSelectionKindV1",
    "UnsupportedCaseParametersV1",
    "W3BuildIssueV1",
    "W3BuildStatusV1",
    "build_etabs_result_catalogue_v1",
    "BeamAuditApplicabilityBasisV1",
    "BeamAuditCheckV1",
    "BeamAuditEvaluationRequestV1",
    "BeamAuditEvaluationResultV1",
    "BeamAuditInputBuildRequestV1",
    "BeamAuditInputBuildResultV1",
    "BeamAuditInputsV1",
    "BeamAuditMemberBasisV1",
    "BeamAuditRowEvaluationRequestV1",
    "BeamAuditRowEvaluationResultV1",
    "BeamAuditRowInputV1",
    "BeamAuditRowResultV1",
    "build_beam_audit_inputs_v1",
    "canonical_beam_action_row_sha256_v1",
    "evaluate_beam_audit_row_v1",
    "evaluate_beam_audit_v1",
    "BeamCandidateCheckEvidenceV2",
    "BeamCandidateCheckResultV2",
    "BeamCandidateCompositionV2",
    "BeamCandidateDefinitionDraftV2",
    "BeamCandidateDefinitionV2",
    "BeamCandidateEvaluationResultV2",
    "build_beam_candidate_definition_v2",
    "check_beam_candidate_composition_v2",
    "evaluate_beam_candidate_v2",
    "BeamCandidateProjectionV1",
    "BeamCandidateSearchDomainDraftV1",
    "BeamCandidateSearchDomainV1",
    "BeamCandidateSearchRequestV1",
    "BeamCandidateSearchResultV1",
    "OptimizationSearchBudgetV1",
    "build_beam_candidate_search_domain_v1",
    "search_beam_candidates_v1",
    "BeamCriteriaScenarioV1",
    "BeamCriteriaStopPolicyV1",
    "BeamExistingPropertyDraftV1",
    "BeamExistingPropertyV1",
    "BeamLongitudinalLayerV1",
    "BeamLongitudinalStockV1",
    "BeamMemberReinforcementScheduleDraftV1",
    "BeamMemberReinforcementScheduleV1",
    "BeamPropertyCostBasisV1",
    "BeamTransverseStockV1",
    "BeamTransverseZoneV1",
    "ProjectBeamCandidateCatalogueDraftV1",
    "ProjectBeamCandidateCatalogueV1",
    "ProjectBeamCriteriaDraftV1",
    "ProjectBeamCriteriaV1",
    "build_beam_existing_property_v1",
    "build_beam_member_reinforcement_schedule_v1",
    "build_project_beam_candidate_catalogue_v1",
    "build_project_beam_criteria_v1",
    "ETABSConcreteDesignBasisDraftV1",
    "ETABSConcreteDesignBasisV1",
    "ETABSDesignSettingV1",
    "ETABSExportBoundsV1",
    "ETABSInstalledSQLiteEvidenceV1",
    "ETABSRequestedTableV1",
    "ETABSSQLiteColumnInventoryV1",
    "ETABSSQLiteExportManifestDraftV1",
    "ETABSSQLiteExportManifestV1",
    "ETABSSQLiteRequestedFieldResolutionV1",
    "ETABSSQLiteRequestedTableResolutionV1",
    "ETABSSQLiteSchemaInventoryV1",
    "ETABSSQLiteTableInventoryV1",
    "build_etabs_installed_sqlite_evidence_v1",
    "build_etabs_concrete_design_basis_v1",
    "finalize_etabs_sqlite_export_manifest_v1",
    "inventory_etabs_sqlite_export_v1",
    "ETABSInstalledReadOnlyCaptureV1",
    "ETABSInstalledReadOnlyReaderV1",
    "ETABSInstalledReadOnlyRunV1",
    "capture_etabs_installed_readonly_v1",
    "etabs_state_content_sha256_v1",
    "run_etabs_installed_readonly_v1",
    "ETABSArtifactIdentityV1",
    "ETABSBrokerResultV1",
    "ETABSCallLedgerIdentityV1",
    "ETABSCallLedgerV1",
    "ETABSCallRecordV1",
    "ETABSEvidenceBundleV1",
    "ETABSLeaseHandleV1",
    "ETABSOperationLeaseV1",
    "ETABSOperationOutcomeV1",
    "acquire_etabs_operation_lease_v1",
    "build_etabs_operation_outcome_v1",
    "finalize_etabs_evidence_bundle_v1",
    "invoke_recorded_etabs_call_v1",
    "run_etabs_sta_broker_v1",
    "verify_etabs_call_ledger_v1",
    "verify_etabs_evidence_bundle_v1",
    "ETABSAccessModeV1",
    "ETABSAttachedStateReaderV1",
    "ETABSBridgeCapabilityV1",
    "ETABSExpectedModelIntentV1",
    "ETABSFileIdentityV1",
    "ETABSInstalledReadOnlyPreflightV1",
    "ETABSModelFreshnessDispositionV1",
    "ETABSModelFreshnessV1",
    "ETABSProcessInstanceV1",
    "ETABSResultEpochDispositionV1",
    "ETABSResultEpochV1",
    "ETABSRuntimeArtifactV1",
    "ETABSRuntimeFingerprintV1",
    "ETABSSavedCheckpointV1",
    "ETABSSessionIdentityV1",
    "ETABSStateSnapshotV1",
    "ETABSTargetObservationV1",
    "ProcessObservationV1",
    "assess_attached_output_readiness_v1",
    "build_etabs_result_epoch_v1",
    "build_etabs_runtime_fingerprint_v1",
    "build_etabs_saved_checkpoint_v1",
    "build_etabs_session_identity_v1",
    "capture_attached_etabs_state_v1",
    "capture_etabs_state_v1",
    "classify_etabs_model_freshness_v1",
    "compare_attached_etabs_state_v1",
    "discover_etabs_processes_v1",
    "file_identity_v1",
    "issue_etabs_bridge_capability_v1",
    "observe_etabs_target_v1",
    "preflight_installed_etabs_readonly_v1",
    "verify_etabs_bridge_capability_v1",
    "verify_etabs_target_observation_v1",
    "canonical_beam_demand_snapshot_hash_basis_json_v1",
    "canonical_etabs_result_catalogue_hash_basis_json_v1",
    "derive_beam_demand_snapshot_v1",
    "extract_etabs_result_catalogue_v1",
    "query_beam_action_rows_v1",
    "run_etabs_live_catalogue_v1",
    "verify_beam_demand_snapshot_hash_v1",
    "verify_etabs_result_catalogue_hash_v1",
    # Modules
    "adapters",
    "api",
    "audit",
    "batch",
    "compliance",
    "costing",
    "design",
    "detailing",
    "dxf_export",
    "etabs_import",
    "flexure",
    "imports",
    "inputs",
    "models",
    "rebar",
    "reports",
    "result_base",
    "serialization",
    "serviceability",
    "shear",
    "testing_strategies",
    "types",
    # Version
    "get_library_version",
    # Diagnostics (TASK-725)
    "show_versions",
    "VersionInfo",
    # Validation
    "validate_job_spec",
    "validate_design_results",
    # Core design functions
    "design_beam_is456",
    "EffectiveDepthBasisV1",
    "EffectiveDepthResolutionV1",
    "design_flanged_beam_is456",
    "check_beam_is456",
    "detail_beam_is456",
    "design_and_detail_beam_is456",
    # Return types
    "ComplianceCaseResult",
    "ComplianceReport",
    "DesignAndDetailResult",
    "FlangedBeamDesignResult",
    # Input dataclasses
    "BeamInput",
    "BeamGeometryInput",
    "MaterialsInput",
    "LoadsInput",
    "LoadCaseInput",
    "DetailingConfigInput",
    "design_from_input",
    # Audit & Verification
    "AuditTrail",
    "AuditLogEntry",
    "CalculationHash",
    "compute_hash",
    "create_calculation_certificate",
    "verify_calculation",
    # Calculation Report
    "CalculationReport",
    "ProjectInfo",
    "InputSection",
    "ResultSection",
    "generate_calculation_report",
    # Outputs
    "compute_detailing",
    "build_detailing_input",
    "calculate_development_length",
    "calculate_development_length_unrounded",
    "check_anchorage_at_simple_support",
    "TensionBarAnchorageResultV1",
    "evaluate_tension_bar_anchorage_v1",
    "compute_bbs",
    "export_bbs",
    "compute_dxf",
    "compute_report",
    "compute_critical",
    # Serviceability
    "check_beam_ductility",
    "check_beam_slenderness",
    "check_deflection_span_depth",
    "check_crack_width",
    "check_compliance_report",
    # Validation
    "ValidationReport",
    # Shear (IS 456 Clause 40)
    "enhanced_shear_strength_is456",
    # Smart features
    "CostProfile",
    "OptimizationConstraints",
    "OptimizationInfeasibleError",
    "optimize_beam_cost",
    "suggest_beam_design_improvements",
    "smart_analyze_design",
    # Multi-objective optimization
    "optimize_pareto_front",
    "ParetoOptimizationResult",
    "ParetoCandidate",
    # Torsion Design (IS 456 Clause 41)
    "design_torsion",
    "calculate_equivalent_shear",
    "calculate_equivalent_moment",
    "calculate_torsion_shear_stress",
    "calculate_torsion_stirrup_area",
    "calculate_longitudinal_torsion_steel",
    "TorsionResult",
    # ETABS Integration (CSV Import)
    "validate_etabs_csv",
    "load_etabs_csv",
    "normalize_etabs_forces",
    "create_job_from_etabs",
    "create_jobs_from_etabs_csv",
    "ETABSForceRow",
    "ETABSEnvelopeResult",
    # Load Analysis (BMD/SFD)
    "compute_bmd_sfd",
    "LoadType",
    "LoadDefinition",
    "CriticalPoint",
    "LoadDiagramResult",
    # 3D Visualization
    "Point3D",
    "BeamGeometry",
    "FrameType",
    "DesignDefaults",
    "RebarSegment",
    "RebarPath",
    "StirrupLoop",
    "Beam3DGeometry",
    "compute_rebar_positions",
    "compute_stirrup_path",
    "compute_stirrup_positions",
    "compute_beam_outline",
    "beam_to_3d_geometry",
    # Column Design (IS 456 Cl 25, 39.3, 39.5, 39.7)
    "calculate_additional_moment_is456",
    "calculate_effective_length_is456",
    "classify_column_is456",
    "min_eccentricity_is456",
    "design_column_axial_is456",
    "design_column_is456",
    "design_long_column_is456",
    "design_short_column_uniaxial_is456",
    "pm_interaction_curve_is456",
    "biaxial_bending_check_is456",
    "check_helical_reinforcement_is456",
    "detail_column_is456",
    "EndCondition",
    # IS 13920 Ductile Detailing
    "check_column_ductility_is13920",
    # Footing Design (IS 456 Cl 34)
    "size_footing",
    "bearing_stress_enhancement",
    "check_bearing_pressure",
    "footing_flexure",
    "footing_one_way_shear",
    "footing_punching_shear",
    "FootingBearingResult",
    "BearingPressureCheckResult",
    "BearingStressEnhancementResult",
    "FootingFlexureResult",
    "FootingOneWayShearResult",
    "FootingPunchingResult",
    "check_isolated_footing_load_transfer",
    "LoadTransferResult",
    "design_concentric_isolated_footing_is456",
    "ConcentricIsolatedFootingInput",
    "ConcentricIsolatedFootingResult",
    "FootingDepthCandidate",
    "FootingDirectionalReinforcementDemand",
    "FootingProvenance",
    # Symmetric combined footing (bounded supported case)
    "design_symmetric_combined_footing_is456",
    "SymmetricCombinedFootingDesignInput",
    "SymmetricCombinedFootingDesignProvenance",
    "SymmetricCombinedFootingDesignResult",
    "SymmetricCombinedFootingDesignStatus",
    # Building Gravity Workflow V1
    "BeamReinforcementEvaluationV1",
    "BeamReinforcementSelectionConstraintsV1",
    "LongitudinalBarLayersV1",
    "SuppliedBeamReinforcementV1",
    "evaluate_supplied_beam_reinforcement_v1",
    "GravityBeamDesignBasisV1",
    "GravityBeamReinforcementBasisV1",
    "GravityLongitudinalBarLayersV1",
    "GravityPracticalActionKindV1",
    "GravityPracticalActionReconciliationV1",
    "GravityPracticalActionUnitsV1",
    "GravityPracticalActionV1",
    "GravityWorkflowRequestV1",
    "GravityWorkflowResultV1",
    "GravityWorkflowRunBundleV1",
    "GravityWorkflowDefinitionV1",
    "RectangularGravityWorkflowBuilderInputV1",
    "build_rectangular_gravity_workflow_request_v1",
    "get_gravity_workflow_example_document_v1",
    "get_gravity_workflow_example_request_v1",
    "get_gravity_workflow_definition_v1",
    "run_gravity_workflow_v1",
    "run_gravity_workflow_with_book_v1",
    # Property-line strap footing (bounded supported case)
    "design_property_line_strap_footing_is456",
    "PropertyLineStrapFootingDesignInput",
    "PropertyLineStrapFootingDesignProvenance",
    "PropertyLineStrapFootingDesignResult",
    "PropertyLineStrapFootingDesignStatus",
    # Solid slab design (bounded supported cases)
    "design_one_way_slab_is456",
    "design_complete_one_way_slab_is456",
    "design_continuous_one_way_slab_builtin_is456",
    "design_continuous_one_way_slab_is456",
    "design_two_way_slab_is456",
    "design_two_way_slab_panel_is456",
    "design_two_way_slab_panel_builtin_is456",
    "OneWaySlabDesignResult",
    "CompleteOneWaySlabDesignResult",
    "ContinuousOneWaySlabDesignResult",
    "TwoWaySlabPanelWorkflowResult",
    # Straight-flight staircase (bounded supported case)
    "design_straight_flight_staircase_is456",
    "StraightFlightStaircaseInput",
    "StraightFlightStaircaseProvenance",
    "StraightFlightStaircaseResult",
    # Braced wall (bounded supported case)
    "design_braced_wall_is456",
    "BracedWallDesignInput",
    "BracedWallDesignProvenance",
    "BracedWallDesignResult",
    # Simply supported deep beam (bounded supported case)
    "design_simply_supported_deep_beam_is456",
    "SimplySupportedDeepBeamDesignInput",
    "SimplySupportedDeepBeamDesignProvenance",
    "SimplySupportedDeepBeamDesignResult",
    # Regular interior flat slab (bounded supported case)
    "design_regular_interior_flat_slab_is456",
    "RegularInteriorFlatSlabDesignInput",
    "RegularInteriorFlatSlabDesignProvenance",
    "RegularInteriorFlatSlabDesignResult",
    "RegularInteriorFlatSlabDesignStatus",
    # Capability discovery
    "get_supported_is456_capability_document",
    "get_supported_is456_capabilities",
    "get_supported_is456_semantic_contract",
    "IS456Capability",
    # Application workflow catalogue
    "ComposedWorkflowCapability",
    "WorkflowCatalog",
    "get_workflow_catalog",
    "get_workflow_catalog_document",
    "serialize_workflow_catalog",
    # Self-validation (TASK-724)
    "check_code",
    "CheckCodeReport",
]


def __getattr__(name: str) -> _ModuleType:
    if name in _LAZY_MODULES:
        mod = importlib.import_module(f".{name}", __name__)
        globals()[name] = mod
        return mod
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
